"""cascade delete embeddings

Revision ID: 11421eaba576
Revises: 7d623719a874
Create Date: 2025-09-06 18:41:51.881319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy.vector



# revision identifiers, used by Alembic.
revision: str = '11421eaba576'
down_revision: Union[str, Sequence[str], None] = '7d623719a874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('embeddings_text_embedding_3_large_chunk_id_fkey'), 'embeddings_text_embedding_3_large', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings_text_embedding_3_large', 'chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embeddings_text_embedding_3_large', type_='foreignkey')
    op.create_foreign_key(op.f('embeddings_text_embedding_3_large_chunk_id_fkey'), 'embeddings_text_embedding_3_large', 'chunks', ['chunk_id'], ['id'])
    # ### end Alembic commands ###
