"""cascades in chunksets and chunks

Revision ID: 7d623719a874
Revises: f95ae1613cfc
Create Date: 2025-09-01 03:01:36.755800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = "7d623719a874"
down_revision: Union[str, Sequence[str], None] = "f95ae1613cfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("chunks_chunk_set_id_fkey"), "chunks", type_="foreignkey")
    op.create_foreign_key(
        None, "chunks", "chunksets", ["chunk_set_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chunks", type_="foreignkey")
    op.create_foreign_key(
        op.f("chunks_chunk_set_id_fkey"),
        "chunks",
        "chunksets",
        ["chunk_set_id"],
        ["id"],
    )
    # ### end Alembic commands ###
