"""initial schema

Revision ID: be78615815ca
Revises:
Create Date: 2025-08-31 19:13:57.049656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = "be78615815ca"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.create_table(
        "embedding_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("table_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "etheldocuments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Investigation seminar: case metadata table
    op.create_table(
        "investigation_cases",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("max_stage", sa.Integer(), nullable=False, server_default="5"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_investigation_cases_tenant",
        "investigation_cases",
        ["tenant"],
    )

    # Investigation seminar: maps documents to categories and release stages
    op.create_table(
        "investigation_case_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("case_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("release_stage", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["etheldocuments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_investigation_case_documents_tenant_case",
        "investigation_case_documents",
        ["tenant", "case_id"],
    )
    op.create_index(
        "ix_investigation_case_documents_document_id",
        "investigation_case_documents",
        ["document_id"],
    )
    op.create_index(
        "ix_investigation_case_documents_category",
        "investigation_case_documents",
        ["category"],
    )
    op.create_index(
        "ix_investigation_case_documents_visibility",
        "investigation_case_documents",
        ["visibility"],
    )
    op.create_index(
        "ix_investigation_case_documents_release_stage",
        "investigation_case_documents",
        ["release_stage"],
    )

    op.create_table(
        "chunksets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["etheldocuments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chunk_set_id", sa.Uuid(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chunk_set_id"],
            ["chunksets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "embeddings_text_embedding_3_large",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("embeddings_text_embedding_3_large")
    op.drop_table("chunks")
    op.drop_table("chunksets")

    op.drop_index(
        "ix_investigation_case_documents_release_stage",
        table_name="investigation_case_documents",
    )
    op.drop_index(
        "ix_investigation_case_documents_visibility",
        table_name="investigation_case_documents",
    )
    op.drop_index(
        "ix_investigation_case_documents_category",
        table_name="investigation_case_documents",
    )
    op.drop_index(
        "ix_investigation_case_documents_document_id",
        table_name="investigation_case_documents",
    )
    op.drop_index(
        "ix_investigation_case_documents_tenant_case",
        table_name="investigation_case_documents",
    )
    op.drop_table("investigation_case_documents")

    op.drop_index(
        "ix_investigation_cases_tenant",
        table_name="investigation_cases",
    )
    op.drop_table("investigation_cases")

    op.drop_table("etheldocuments")
    op.drop_table("embedding_models")
    # ### end Alembic commands ###
