"""add text-embedding-3-small

Revision ID: daee4d2eb24c
Revises: 1b89e5ee22d8
Create Date: 2025-11-06 18:08:43.314486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = "daee4d2eb24c"
down_revision: Union[str, Sequence[str], None] = "1b89e5ee22d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embeddings_text_embedding_3_small",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "embeddings_text_embedding_3_small_vector_idx",
        "embeddings_text_embedding_3_small",
        [sa.literal_column("(vector::halfvec(1536)) halfvec_cosine_ops")],
        unique=False,
        postgresql_using="hnsw",
    )
    op.create_index(
        op.f("ix_embeddings_text_embedding_3_small_chunk_id"),
        "embeddings_text_embedding_3_small",
        ["chunk_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_embeddings_text_embedding_3_small_chunk_id"),
        table_name="embeddings_text_embedding_3_small",
    )
    op.drop_index(
        "embeddings_text_embedding_3_small_vector_idx",
        table_name="embeddings_text_embedding_3_small",
        postgresql_using="hnsw",
    )
    op.drop_table("embeddings_text_embedding_3_small")
    # ### end Alembic commands ###
