"""add content type

Revision ID: f95ae1613cfc
Revises: be78615815ca
Create Date: 2025-08-31 22:38:09.337807

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = "f95ae1613cfc"
down_revision: Union[str, Sequence[str], None] = "be78615815ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "etheldocuments",
        sa.Column(
            "content_type",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="application/octet-stream",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("etheldocuments", "content_type")
    # ### end Alembic commands ###
